language: python

services:
  - mysql

python:
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE kevin;'
  - cp .env.travis .env

# command to run tests
script:
  - python manage.py test